### PR TITLE
chore: upgrade axios to to address CSRF issues

### PR DESCRIPTION
**Pull request by liangyuanruo**
## Problem

Addresses failing Snyk upgrade in #295 

## Solution

Upgrade `axios` from `0.24.0` to `^1.6.0`.

TODO: address compilation errors

### CODE REVIEW

**Comment by pregnantboy** [comment]
is there work on this?

**Comment by liangyuanruo** [comment]
@pregnantboy - @ogp-weeloong offered to help with this due to spate of work on ESG side, but I think he is at max bandwidth. will close this PR first until ready for review.
